name: Requirements
on:
  pull_request:
    branches:
      - qa
      - master
      - staging
jobs:
  requirements-backend:
    uses: Pawsly-connect/pawsly-pipeline/.github/workflows/requeriments_backend.yml@master
    secrets: inherit
