name: Requirements
on:
  pull_request:
    branches:
      - qa
      - master
      - staging
jobs:
  runs-on: ubuntu-latest
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Analyze with SonarCloud
      uses: sonarsource/sonarcloud-github-action@master

      with:
        projectBaseDir: src
        args: >
          -Dsonar.organization=pawsly-connect
          -Dsonar.projectKey=pawsly-connect
          -Dsonar.sources=lib/
          -Dsonar.test.exclusions=tests/**
          -Dsonar.tests=tests/
